// Spanish translations. Keys are the English text used in the site.
export default {
  "Services": "Servicios",
  "About": "Nosotros",
  "How It Works": "Cómo funciona",
  "Our work": "Nuestro trabajo",
  "Look at our work": "Mira nuestro trabajo",
  "All services": "Todos los servicios",
  "Other services": "Otros servicios",
  "Drag the slider to see the difference.": "Mueve el control para ver la diferencia.",
  "New photos for this service are coming soon.": "Pronto tendremos nuevas fotos de este servicio.",
  "Our Work": "Nuestro trabajo",
  "Contact": "Contacto",
  "Leave a Review": "Deja una reseña",
  "Call Us": "Llámanos",
  "Get a Quote": "Pide una cotización",
  "Professional Cleaning Services": "Servicios de limpieza profesional",
  "A cleaner space.": "Un espacio más limpio.",
  "More time for you.": "Más tiempo para ti.",
  "Reliable residential and commercial cleaning services designed to give your space the care and attention it deserves.": "Servicios de limpieza residencial y comercial confiables, pensados para darle a tu espacio el cuidado y la atención que merece.",
  "Get a Free Quote": "Cotización gratis",
  "Text Us": "Escríbenos",
  "Professional service": "Servicio profesional",
  "Flexible scheduling": "Horarios flexibles",
  "Free estimates": "Cotizaciones gratis",
  "Fresh. Clean. Ready.": "Fresco. Limpio. Listo.",
  "That's the SL standard.": "Ese es el estándar de SL.",
  "Professional Care": "Cuidado profesional",
  "Attention to Detail": "Atención al detalle",
  "Easy Communication": "Comunicación fácil",
  "Customer Focused": "Enfocados en el cliente",
  "OUR SERVICES": "NUESTROS SERVICIOS",
  "Cleaning that fits your needs.": "Una limpieza a la medida de tus necesidades.",
  "From routine home cleaning to detailed deep cleans, we provide dependable service for spaces that deserve to feel their best.": "Desde la limpieza regular del hogar hasta limpiezas profundas y detalladas, ofrecemos un servicio confiable para espacios que merecen verse y sentirse en su mejor momento.",
  "Get a quote": "Pedir cotización",
  "WHY SL CLEANING": "POR QUÉ SL CLEANING",
  "We don't just clean.": "No solo limpiamos.",
  "We care about the result.": "Nos importa el resultado.",
  "A professional cleaning service should make your life easier. That's why our approach is centered around dependable service, clear communication, and attention to the details.": "Un servicio de limpieza profesional debe hacerte la vida más fácil. Por eso nuestro enfoque se centra en un servicio confiable, comunicación clara y atención a los detalles.",
  "HOW IT WORKS": "CÓMO FUNCIONA",
  "Simple from start to finish.": "Sencillo de principio a fin.",
  "Getting professional cleaning shouldn't be complicated.": "Contratar una limpieza profesional no tiene por qué ser complicado.",
  "OUR WORK": "NUESTRO TRABAJO",
  "See the difference for yourself.": "Mira la diferencia tú mismo.",
  "A look at some of the homes and spaces we've recently cleaned.": "Un vistazo a algunos de los hogares y espacios que hemos limpiado recientemente.",
  "SERVICE AREA": "ÁREA DE SERVICIO",
  "Proudly serving your local community.": "Orgullosos de servir a tu comunidad.",
  "We currently provide cleaning services throughout all of Los Angeles County and all of Orange County. Outside these areas? Reach out anyway — we're happy to see if we can make it work for your location.": "Actualmente ofrecemos servicios de limpieza en todo el condado de Los Ángeles y en todo el condado de Orange. ¿Fuera de estas zonas? Escríbenos de todos modos: con gusto vemos si podemos atender tu ubicación.",
  "All of LA County": "Todo el condado de Los Ángeles",
  "All of Orange County": "Todo el condado de Orange",
  "Outside these areas? Contact us": "¿Fuera de estas zonas? Contáctanos",
  "GET STARTED": "EMPIEZA AHORA",
  "Ready for a cleaner space?": "¿Listo para un espacio más limpio?",
  "Tell us what you need and we'll get back to you with the next steps.": "Cuéntanos qué necesitas y te responderemos con los siguientes pasos.",
  "Call us": "Llámanos",
  "Text us": "Escríbenos",
  "Email us": "Envíanos un correo",
  "FREE QUOTE": "COTIZACIÓN GRATIS",
  "Tell us about your cleaning needs.": "Cuéntanos qué necesitas limpiar.",
  "Your name": "Tu nombre",
  "Phone": "Teléfono",
  "Email": "Correo electrónico",
  "ZIP code": "Código postal",
  "Service": "Servicio",
  "Select a service": "Elige un servicio",
  "Residential Cleaning": "Limpieza residencial",
  "Deep Cleaning": "Limpieza profunda",
  "Move-In / Move-Out": "Mudanza (entrada / salida)",
  "Commercial Cleaning": "Limpieza comercial",
  "Other": "Otro",
  "How often?": "¿Con qué frecuencia?",
  "Select frequency": "Elige la frecuencia",
  "One time": "Una sola vez",
  "Weekly": "Cada semana",
  "Every 2 weeks": "Cada 2 semanas",
  "Monthly": "Cada mes",
  "Not sure yet": "Aún no estoy seguro",
  "Bedrooms": "Recámaras",
  "Not sure / not applicable": "No sé / no aplica",
  "Studio": "Estudio",
  "5 or more": "5 o más",
  "Bathrooms": "Baños",
  "4 or more": "4 o más",
  "Preferred date": "Fecha preferida",
  "Best time of day": "Mejor horario",
  "Flexible": "Flexible",
  "Morning": "Mañana",
  "Afternoon": "Tarde",
  "Tell us more": "Cuéntanos más",
  "No obligation. We'll contact you to discuss your cleaning needs.": "Sin compromiso. Te contactaremos para hablar de lo que necesitas.",
  "Professional cleaning services focused on quality, reliability, and making your space feel its best.": "Servicios de limpieza profesional enfocados en la calidad, la confiabilidad y en que tu espacio se vea y se sienta mejor.",
  "Navigation": "Navegación",
  "Service Area": "Área de servicio",
  "Professional cleaning. Personal care.": "Limpieza profesional. Atención personal.",
  "Call": "Llamar",
  "Text": "Mensaje",
  "Get Free Quote": "Cotización gratis",
  "SL Cleaning Services home": "SL Cleaning Services, inicio",
  "Main navigation": "Navegación principal",
  "Mobile navigation": "Navegación móvil",
  "Living room and kitchen after a professional clean": "Sala y cocina después de una limpieza profesional",
  "Kitchen after a professional deep clean": "Cocina después de una limpieza profunda profesional",
  "John Smith": "Juan Pérez",
  "you@example.com": "tu@ejemplo.com",
  "Tell us about your space and what you need cleaned...": "Cuéntanos sobre tu espacio y qué necesitas limpiar...",
  "RATE YOUR SERVICE": "CALIFICA TU SERVICIO",
  "How did we do?": "¿Cómo lo hicimos?",
  "We'd love your feedback on the work we completed. It helps us keep our standards high and helps other clients know what to expect.": "Nos encantaría conocer tu opinión sobre el trabajo que realizamos. Nos ayuda a mantener nuestros estándares altos y a que otros clientes sepan qué esperar.",
  "SERVICE SURVEY": "ENCUESTA DE SERVICIO",
  "Tell us about the work we did for you.": "Cuéntanos sobre el trabajo que hicimos para ti.",
  "Disclaimer:": "Aviso:",
  "the person filling out this form must be the person who supervised how the work was done (owner, manager, or on-site supervisor).": "la persona que llene este formulario debe ser quien supervisó cómo se realizó el trabajo (dueño, gerente o supervisor en el sitio).",
  "Your role on site": "Tu puesto en el sitio",
  "Select your role": "Elige tu puesto",
  "Owner": "Dueño",
  "Manager": "Gerente",
  "Supervisor": "Supervisor",
  "Address where the work was done": "Dirección donde se realizó el trabajo",
  "Date of service": "Fecha del servicio",
  "Would you recommend us?": "¿Nos recomendarías?",
  "Select an answer": "Elige una respuesta",
  "Yes": "Sí",
  "No": "No",
  "Overall rating": "Calificación general",
  "Additional comments": "Comentarios adicionales",
  "Submit Survey": "Enviar encuesta",
  "Your feedback goes directly to our team and is not published without your permission.": "Tu opinión llega directamente a nuestro equipo y no se publica sin tu permiso.",
  "Submitting your survey...": "Enviando tu encuesta...",
  "Please hold on a moment.": "Espera un momento, por favor.",
  "Thanks for your survey!": "¡Gracias por tu encuesta!",
  "We really appreciate you taking the time to share your feedback with us.": "Agradecemos mucho que te tomes el tiempo de compartir tu opinión.",
  "Go back home": "Volver al inicio",
  "Leave the website": "Salir del sitio",
  "You're all set — you can close this tab now.": "Todo listo: ya puedes cerrar esta pestaña.",
  "Street, City, ZIP": "Calle, Ciudad, Código postal",
  "Anything you'd like to share about the service...": "Cualquier cosa que quieras compartir sobre el servicio...",
  "A dependable clean for kitchens, bathrooms, bedrooms, living spaces, and the details that make your home feel fresh.": "Una limpieza confiable de cocinas, baños, recámaras, salas y los detalles que hacen que tu hogar se sienta fresco.",
  "A more detailed clean for homes that need extra attention, including hard-to-reach areas and built-up dirt.": "Una limpieza más detallada para hogares que necesitan atención extra, incluidas las zonas difíciles de alcanzar y la suciedad acumulada.",
  "Get your space ready for the next chapter with a thorough clean before moving in or handing over the keys.": "Deja tu espacio listo para la siguiente etapa con una limpieza a fondo antes de mudarte o de entregar las llaves.",
  "Professional cleaning support for offices and other commercial spaces that need a clean, presentable environment.": "Apoyo de limpieza profesional para oficinas y otros espacios comerciales que necesitan un ambiente limpio y presentable.",
  "Reliable Service": "Servicio confiable",
  "We believe showing up on time and communicating clearly should be part of every professional cleaning experience.": "Creemos que llegar a tiempo y comunicarse con claridad debe ser parte de toda experiencia de limpieza profesional.",
  "We focus on the areas that are easy to overlook so your space feels genuinely clean—not just quickly cleaned.": "Nos enfocamos en las zonas que es fácil pasar por alto, para que tu espacio se sienta realmente limpio y no solo limpiado a la carrera.",
  "Flexible Cleaning": "Limpieza flexible",
  "Choose the type of cleaning that fits your home, schedule, and specific needs.": "Elige el tipo de limpieza que se ajuste a tu hogar, tu horario y tus necesidades.",
  "Request a Quote": "Solicita una cotización",
  "Tell us a little about your space and the cleaning service you need.": "Cuéntanos un poco sobre tu espacio y el servicio de limpieza que necesitas.",
  "Choose Your Service": "Elige tu servicio",
  "We'll help you determine the right cleaning option for your needs.": "Te ayudamos a elegir la opción de limpieza adecuada para ti.",
  "We Clean": "Nosotros limpiamos",
  "Our team arrives ready to leave your space looking fresh and cared for.": "Nuestro equipo llega listo para dejar tu espacio fresco y bien cuidado.",
  "Kitchen Deep Clean": "Limpieza profunda de cocina",
  "Living Room Refresh": "Renovación de sala",
  "Bathroom Detail Clean": "Limpieza detallada de baño",
  "Bedroom Tidy & Clean": "Orden y limpieza de recámara",
  "Move-Out Cleaning": "Limpieza de mudanza",
  "Outside Cleaning": "Limpieza de exteriores",
  "Switch language": "Cambiar idioma",
  "Switch to dark mode": "Cambiar a modo noche",
  "Switch to light mode": "Cambiar a modo día",
  "Close menu": "Cerrar menú",
  "Open menu": "Abrir menú",
  "All rights reserved.": "Todos los derechos reservados.",
  "Serving LA & Orange County": "Atendemos LA y el condado de Orange",
  "star": "estrella",
  "stars": "estrellas",
  "Sending...": "Enviando...",
  "Thank you! Your quote request has been sent successfully.": "¡Gracias! Tu solicitud de cotización se envió correctamente.",
  "Something went wrong. Please try again.": "Algo salió mal. Inténtalo de nuevo.",
  "Unable to send your request. Please try again.": "No pudimos enviar tu solicitud. Inténtalo de nuevo.",
  "Unable to send your survey. Please try again.": "No pudimos enviar tu encuesta. Inténtalo de nuevo.",
  "Please select a star rating.": "Elige una calificación de estrellas.",
  "REVIEWS": "RESEÑAS",
  "What our customers say.": "Lo que dicen nuestros clientes.",
  "Review us on Google": "Déjanos una reseña en Google",
  "BEFORE & AFTER": "ANTES Y DESPUÉS",
  "Drag to see the difference.": "Desliza para ver la diferencia.",
  "Before": "Antes",
  "After": "Después",
  "Compare before and after:": "Comparar antes y después:",
  "QUESTIONS": "PREGUNTAS",
  "Frequently asked questions.": "Preguntas frecuentes.",
  "Residential cleaning": "Limpieza residencial",
  "Kitchens, bathrooms, bedrooms and living spaces.": "Cocinas, baños, recámaras y salas.",
  "Deep cleaning": "Limpieza profunda",
  "Extra attention for built-up dirt and hard-to-reach areas.": "Atención extra para la suciedad acumulada y las zonas difíciles de alcanzar.",
  "Move-in / move-out cleaning": "Limpieza de mudanza (entrada / salida)",
  "A thorough clean before you move in or hand over the keys.": "Una limpieza a fondo antes de mudarte o de entregar las llaves.",
  "Commercial cleaning": "Limpieza comercial",
  "Offices and other commercial spaces.": "Oficinas y otros espacios comerciales.",
  "House & Commercial Cleaning in {city} | {name}": "Limpieza residencial y comercial en {city} | {name}",
  "Page not found | {name}": "Página no encontrada | {name}",
  "{name} provides residential, deep, move-out and commercial cleaning in {city}, {county}. Get a free quote.": "{name} ofrece limpieza residencial, profunda, de mudanza y comercial en {city}, {county}. Pide tu cotización gratis.",
  "Cleaning services in {city}": "Servicios de limpieza en {city}",
  "{name} provides residential and commercial cleaning in {city} and throughout {county}. Tell us what you need and we'll get back to you with next steps.": "{name} ofrece limpieza residencial y comercial en {city} y en todo {county}. Cuéntanos qué necesitas y te responderemos con los siguientes pasos.",
  "What we clean in {city}": "Qué limpiamos en {city}",
  "Other areas we serve": "Otras zonas que atendemos",
  "Page not found": "Página no encontrada",
  "We couldn't find that page.": "No encontramos esa página.",
  "Back to home": "Volver al inicio",
  "Call {phone}": "Llamar al {phone}",
  "Los Angeles County": "el condado de Los Ángeles",
  "Orange County": "el condado de Orange",
  "SL Cleaning Services | Residential & Commercial Cleaning in LA & Orange County": "SL Cleaning Services | Limpieza residencial y comercial en LA y el condado de Orange",
  "Professional residential and commercial cleaning services throughout all of LA County and Orange County. Reliable, detail-focused, and easy to book. Get a free quote today.": "Servicios profesionales de limpieza residencial y comercial en todo el condado de Los Ángeles y el condado de Orange. Confiables, detallistas y fáciles de reservar. Pide tu cotización gratis hoy.",
  "Request My Free Quote": "Solicitar mi cotización gratis"
};
